In [1]:
import torch

torch.dtype

In [15]:
??torch.rand

Docstring:
rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func

In [14]:
a = torch.rand(5, 3)

In [7]:
a.dtype

torch.float32

In [16]:
x = torch.ones(2, 2, requires_grad=True)

In [17]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [18]:
y = x + 2

In [19]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [20]:
z = y * y * 3

In [21]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [25]:
out = z.mean()

In [26]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [28]:
out.backward()

In [29]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [30]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 674.2732, -563.5367,  560.9821], grad_fn=<MulBackward0>)


In [34]:
y.backward(x)

In [35]:
x.grad

tensor([ 674.2732, -563.5367,  560.9821])

In [36]:
x.requires_grad = False

In [41]:
x = torch.randn(3, requires_grad=False)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1266.6588, -627.3674,  707.8732])


In [42]:
y.backward(x)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn